apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: vitoriaemanuely/user-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: MongoDb__ConnectionString
          value: "mongodb://my-mongo-mongodb:27017"
        - name: MongoDb__DatabaseName
          value: "UserDb"
